name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        rakudo-version:
          - "latest"
          - "2023.12"
      fail-fast: false
    uses: vrurg/raku-build-tools/.github/workflows/default-test-workflow.yml@workflow-v3
    with:
      os: ${{ matrix.os }}
      rakudo-version: ${{ matrix.rakudo-version }}
